export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_ERROR = 'FETCH_ALL_USERS_ERROR';

export const FETCH_FULL_INFO_USER_SUCCESS = 'FETCH_FULL_INFO_USER_SUCCESS';
export const FETCH_FULL_INFO_USER_FAILURE = 'FETCH_FULL_INFO_USER_FAILURE';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_ERROR = 'FACEBOOK_LOGIN_ERROR';

export const VK_LOGIN_SUCCESS = 'VK_LOGIN_SUCCESS';
export const VK_LOGIN_ERROR = 'VK_LOGIN_ERROR';

export const RECOVER_PASSWORD_FAILURE = 'RECOVER_PASSWORD_FAILURE';
export const CHECK_TOKEN_FAILURE = 'CHECK_TOKEN_FAILURE';
export const CHANGE_PASS_FAILURE = 'CHANGE_PASS_FAILURE';

export const ADD_NEW_SECTION_SUCCESS = 'ADD_NEW_SECTION_SUCCESS';
export const ADD_NEW_SECTION_ERROR = 'ADD_NEW_SECTION_ERROR';

export const GET_FINISHED_SECTION_SUCCESS = 'GET_FINISHED_SECTION_SUCCESS';
export const GET_FINISHED_SECTION_FAILURE = 'GET_FINISHED_SECTION_FAILURE';

export const FETCH_ALL_BLOCKS_SUCCESS = 'FETCH_ALL_BLOCKS_SUCCESS';
export const FETCH_ALL_BLOCKS_ERROR = 'FETCH_ALL_BLOCKS_ERROR';

export const FETCH_RESULTS_SUCCESS = 'FETCH_RESULTS_SUCCESS';
export const FETCH_RESULTS_ERROR = 'FETCH_RESULTS_ERROR';

export const GET_BLOCK_BY_ID_SUCCESS = 'GET_BLOCK_BY_ID_SUCCESS';
export const GET_BLOCK_BY_ID_ERROR = 'GET_BLOCK_BY_ID_ERROR';

export const FETCH_ALL_SECTIONS_SUCCESS = 'FETCH_ALL_SECTIONS_SUCCESS';
export const FETCH_ALL_SECTIONS_ERROR = 'FETCH_ALL_SECTIONS_ERROR';
export const DELETE_SECTION_FAILURE = 'DELETE_SECTION_FAILURE';

export const SUBMIT_SECTION_SUCCESS = 'SUBMIT_SECTION_SUCCESS';
export const SUBMIT_SECTION_ERROR = 'SUBMIT_SECTION_ERROR';

export const TOGGLE_SECTION_FORM = 'TOGGLE_SECTION_FORM';

export const TOGGLE_RATEMODAL = 'TOGGLE_RATEMODAL';

export const SUCCESS_SETTED_RATING_SECTION = 'SUCCESS_SETTED_RATING_SECTION';
export const SUCCESS_SETTED_RATING_SECTION_FAILURE = 'SUCCESS_SETTED_RATING_SECTION_FAILURE';

export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_FAILURE = 'ADD_QUESTION_FAILURE';
export const ADD_TEST_QUESTION_FAILURE = 'ADD_TEST_QUESTION_FAILURE';

export const ADD_OPTION_SUCCESS = 'ADD_OPTION_SUCCESS';
export const ADD_OPTION_ERROR = 'ADD_OPTION_ERROR';

export const NOTIFY_ADMIN_SUCCESS = 'NOTIFY_ADMIN_SUCCESS';
export const NOTIFY_ADMIN_FAILURE = 'NOTIFY_ADMIN_FAILURE';

export const ADD_QUESTIONS_FROM_SECTION = 'ADD_QUESTIONS_FROM_SECTION';

export const ANSWER_DRAW_QUESTION = 'ANSWER_DRAW_QUESTION';

export const GET_QUESTION_BY_ID_SUCCESS = 'GET_QUESTION_BY_ID_SUCCESS';
export const GET_SECTION_BY_ID_SUCCESS = 'GET_SECTION_BY_ID_SUCCESS';
export const GET_SECTION_BY_ID_FAILURE = 'GET_SECTION_BY_ID_FAILURE';
export const EDIT_SECTION_FAILURE = 'EDIT_SECTION_FAILURE';
export const ADD_NEW_SECTION_FAILURE = 'ADD_NEW_SECTION_FAILURE';

export const GET_QUESTION_BY_ID_FAILURE = 'GET_QUESTION_BY_ID_FAILURE';
export const DELETE_QUESTION_FAILURE = 'DELETE_QUESTION_FAILURE';
export const EDIT_QUESTION_FAILURE = 'EDIT_QUESTION_FAILURE';

export const GET_PSYCHOLOGISTS = 'GET_PSYCHOLOGISTS';
export const GET_PSYCHOLOGISTS_FAILURE = 'GET_PSYCHOLOGISTS_FAILURE';
export const GET_PSYCHO_BY_ID = 'GET_PSYCHO_BY_ID';
export const GET_PSYCHO_BY_ID_FAILURE = 'GET_PSYCHO_BY_ID_FAILURE';

export const ADD_PSYCHO_FAILURE = 'ADD_PSYCHO_FAILURE';
export const EDIT_PSYCHO_FAILURE = 'EDIT_PSYCHO_FAILURE';
export const DELETE_PSYCHO_FAILURE = 'DELETE_PSYCHO_FAILURE';

export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';

export const FETCH_NOTIFICATIONS_ADMIN_SUCCESS = 'FETCH_NOTIFICATIONS_ADMIN_SUCCESS';
export const FETCH_NOTIFICATIONS_ADMIN_FAILURE = 'FETCH_NOTIFICATIONS_ADMIN_FAILURE';

export const ANALYSE_TEST_RESULTS_SUCCESS = 'ANALYSE_TEST_RESULTS_SUCCESS';
export const ANALYSE_TEST_RESULTS_FAILURE = 'ANALYSE_TEST_RESULTS_FAILURE';

export const FETCH_ALL_REVIEWS_SUCCESS = 'FETCH_ALL_REVIEWS_SUCCESS';
export const FETCH_ALL_REVIEWS_FAILURE = 'FETCH_ALL_REVIEWS_FAILURE';
export const SEND_REVIEW_FAILURE = 'SEND_REVIEW_FAILURE';

export const FETCH_PSYCHOLOGIST_REVIEWS_SUCCESS = 'FETCH_PSYCHOLOGIST_REVIEWS_SUCCESS';
export const FETCH_PSYCHOLOGIST_REVIEWS_FAILURE = 'FETCH_PSYCHOLOGIST_REVIEWS_FAILURE';

export const IS_LOADING = 'IS_LOADING';

export const GET_USER_NOTIFICATIONS_SUCCESS = 'GET_USER_NOTIFICATIONS_SUCCESS';
export const GET_USER_NOTIFICATIONS_FAILURE = 'GET_USER_NOTIFICATIONS_FAILURE';
export const GET_IMPORTANT_USERS = 'GET_IMPORTANT_USERS';
export const GET_IMPORTANT_USERS_FAILURE = 'GET_IMPORTANT_USERS_FAILURE';

export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACT_ID_SUCCESS = 'GET_CONTACT_ID_SUCCESS';
export const GET_CONTACTS_FAILURE = 'GET_CONTACTS_FAILURE';
export const GET_CONTACT_ID_FAILURE = 'GET_CONTACT_ID_FAILURE';
export const EDIT_CONTACTS_FAILURE = 'EDIT_CONTACTS_FAILURE';

export const GET_ABOUT_INFO = 'GET_ABOUT_INFO';
export const GET_ABOUT_INFO_FAILURE = 'GET_ABOUT_INFO_FAILURE';
export const EDIT_INFO_FAILURE = 'EDIT_INFO_FAILURE';